# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\nurhat\Desktop\bütce\add_income_expense.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddIncomeExpenseDialog(object):
    def setupUi(self, AddIncomeExpenseDialog):
        AddIncomeExpenseDialog.setObjectName("AddIncomeExpenseDialog")
        AddIncomeExpenseDialog.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(AddIncomeExpenseDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 100, 30))
        self.label.setObjectName("label")
        self.category_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.category_combobox.setGeometry(QtCore.QRect(150, 30, 200, 30))
        self.category_combobox.setObjectName("category_combobox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 100, 30))
        self.label_2.setObjectName("label_2")
        self.amount_input = QtWidgets.QLineEdit(self.centralwidget)
        self.amount_input.setGeometry(QtCore.QRect(150, 80, 200, 30))
        self.amount_input.setObjectName("amount_input")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 100, 30))
        self.label_3.setObjectName("label_3")
        self.type_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.type_combobox.setGeometry(QtCore.QRect(150, 130, 200, 30))
        self.type_combobox.setObjectName("type_combobox")
        self.type_combobox.addItem("")
        self.type_combobox.addItem("")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(150, 200, 100, 30))
        self.add_btn.setObjectName("add_btn")

        self.retranslateUi(AddIncomeExpenseDialog)
        QtCore.QMetaObject.connectSlotsByName(AddIncomeExpenseDialog)

    def retranslateUi(self, AddIncomeExpenseDialog):
        _translate = QtCore.QCoreApplication.translate
        AddIncomeExpenseDialog.setWindowTitle(_translate("AddIncomeExpenseDialog", "Gelir/Gider Ekle"))
        self.label.setText(_translate("AddIncomeExpenseDialog", "Kategori:"))
        self.label_2.setText(_translate("AddIncomeExpenseDialog", "Tutar:"))
        self.label_3.setText(_translate("AddIncomeExpenseDialog", "Tür:"))
        self.type_combobox.setItemText(0, _translate("AddIncomeExpenseDialog", "Gelir"))
        self.type_combobox.setItemText(1, _translate("AddIncomeExpenseDialog", "Gider"))
        self.add_btn.setText(_translate("AddIncomeExpenseDialog", "Ekle"))
