# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\nurhat\Desktop\bütce\create_category.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateCategoryDialog(object):
    def setupUi(self, CreateCategoryDialog):
        CreateCategoryDialog.setObjectName("CreateCategoryDialog")
        CreateCategoryDialog.resize(400, 200)
        self.centralwidget = QtWidgets.QWidget(CreateCategoryDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 100, 30))
        self.label.setObjectName("label")
        self.category_name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.category_name_input.setGeometry(QtCore.QRect(150, 30, 200, 30))
        self.category_name_input.setObjectName("category_name_input")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(150, 100, 100, 30))
        self.add_btn.setObjectName("add_btn")

        self.retranslateUi(CreateCategoryDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateCategoryDialog)

    def retranslateUi(self, CreateCategoryDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateCategoryDialog.setWindowTitle(_translate("CreateCategoryDialog", "Kategori Oluştur"))
        self.label.setText(_translate("CreateCategoryDialog", "Kategori Adı:"))
        self.add_btn.setText(_translate("CreateCategoryDialog", "Ekle"))
