# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\nurhat\Desktop\bütce\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_income_expense_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_income_expense_btn.setGeometry(QtCore.QRect(30, 30, 200, 50))
        self.add_income_expense_btn.setObjectName("add_income_expense_btn")
        self.create_category_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_category_btn.setGeometry(QtCore.QRect(30, 100, 200, 50))
        self.create_category_btn.setObjectName("create_category_btn")
        self.view_analysis_btn = QtWidgets.QPushButton(self.centralwidget)
        self.view_analysis_btn.setGeometry(QtCore.QRect(30, 170, 200, 50))
        self.view_analysis_btn.setObjectName("view_analysis_btn")
        self.categories_list = QtWidgets.QListWidget(self.centralwidget)
        self.categories_list.setGeometry(QtCore.QRect(250, 30, 500, 300))
        self.categories_list.setObjectName("categories_list")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bütçe Takip Programı"))
        self.add_income_expense_btn.setText(_translate("MainWindow", "Gelir/Gider Ekle"))
        self.create_category_btn.setText(_translate("MainWindow", "Kategori Oluştur"))
        self.view_analysis_btn.setText(_translate("MainWindow", "Analiz Görüntüle"))
