# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\nurhat\Desktop\bütce\view_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnalysisDialog(object):
    def setupUi(self, AnalysisDialog):
        AnalysisDialog.setObjectName("AnalysisDialog")
        AnalysisDialog.resize(600, 400)
        self.label = QtWidgets.QLabel(AnalysisDialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 100, 30))
        self.label.setObjectName("label")
        self.analysis_table = QtWidgets.QTableWidget(AnalysisDialog)
        self.analysis_table.setGeometry(QtCore.QRect(30, 80, 540, 250))
        self.analysis_table.setObjectName("analysis_table")
        self.analysis_table.setColumnCount(0)
        self.analysis_table.setRowCount(0)
        self.analysis_result = QtWidgets.QLabel(AnalysisDialog)
        self.analysis_result.setGeometry(QtCore.QRect(30, 340, 540, 50))
        self.analysis_result.setObjectName("analysis_result")

        self.retranslateUi(AnalysisDialog)
        QtCore.QMetaObject.connectSlotsByName(AnalysisDialog)

    def retranslateUi(self, AnalysisDialog):
        _translate = QtCore.QCoreApplication.translate
        AnalysisDialog.setWindowTitle(_translate("AnalysisDialog", "Analiz Görüntüle"))
        self.label.setText(_translate("AnalysisDialog", "Analiz:"))
